FROM golang:alpine as builder
MAINTAINER Jack Murdock <jack_murdock@comcast.com>

WORKDIR /go/src/github.com/xmidt-org/talaria

RUN apk add --update git curl

COPY . .

RUN go build -o talaria_linux_amd64

FROM alpine

RUN apk --no-cache add ca-certificates
RUN mkdir -p /etc/talaria
VOLUME /etc/talaria

EXPOSE 8080

COPY --from=builder /go/src/github.com/xmidt-org/talaria/talaria_linux_amd64 /
COPY talaria.yaml /
ENTRYPOINT ["/talaria_linux_amd64"]