# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Approve Dependabot'

on:
  pull_request_target:

jobs:
  dependabot:
    uses: xmidt-org/shared-go/.github/workflows/approve-dependabot.yml@2927c6f3ebb0f1fb32856842d21a3ef4ed80efe6 # v4.9.36
    secrets: inherit
