# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - MAINTAINERS.md
      - LICENSE
      - NOTICE
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: xmidt-org/shared-go/.github/workflows/ci.yml@3b93a21a0be3965e2f9e148c627fcee0c06a4cb6 # v4.4.6
    with:
      style-skip:            true
      release-type:          program
      release-arch-arm64:    false
      release-docker:        true
      release-docker-latest: true
      release-docker-major:  true
      release-docker-minor:  true
      release-docker-extras: |
        .release/docker
        LICENSE
        NOTICE
      yaml-lint-skip: false
    secrets: inherit
